#include "stdio.h"
#include "pbc.h"
#include "gmp.h"
#include "time.h"
#include "openssl/sha.h"
#include "string.h"
#include <stdlib.h> 
#include <openssl/evp.h> 
#include <math.h>



 typedef struct {
    element_t PID1i;
    element_t PID2i;
    element_t ai;
    element_t U;
    element_t xi;
    element_t Xi;
} Vehicle;/*A Vehicle*/
 
int sha1_160bit_hash(char *hex_hash, const unsigned char *message, size_t msg_len)
{
   
    if (hex_hash == NULL) {
        return -1;
    }

    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    if (!ctx) {
        return -2;
    }

    unsigned char hash_bin[20];  //(160-bit)
    unsigned int hash_len;

    //initialize 
    if (EVP_DigestInit_ex(ctx, EVP_sha1(), NULL) != 1) {
        EVP_MD_CTX_free(ctx);
        return -3;
    }

    // 2. add data
    EVP_DigestUpdate(ctx, message, msg_len);

    // 3. Compute binary hash
    EVP_DigestFinal_ex(ctx, hash_bin, &hash_len);
    EVP_MD_CTX_free(ctx);

    // ==============================================
    // The hash function hex_hash
    // ==============================================
    for (int i = 0; i < 20; i++) {
        sprintf(hex_hash + i*2, "%02x", hash_bin[i]);
    }
    hex_hash[40] = '\0';  

    return 0; 
}

int hash_to_zr(element_t z, const unsigned char *data, size_t len) {
    char h[512];
    sha1_160bit_hash(h, data, len);
    element_from_bytes(z, h);
    return 0;
}/*Convert hash value h to an element z in Zr*/

int H1(element_t out, element_t PID1i, element_t PID2i, element_t Xi) {
    char buf[512];
    int pos = 0;
    pos += element_to_bytes(buf + pos, PID1i);
    pos += element_to_bytes(buf + pos, PID2i);
    pos += element_to_bytes(buf + pos, Xi);
    hash_to_zr(out, buf, pos);
}/*Hash function H1*/

int H2(element_t B, unsigned char *data){
    element_from_hash(B, data, 20);
    return 0;
}

int H3(element_t out, element_t PID1i, element_t PID2i, element_t B, const char *data, const char *t){
    char buf[1256];
    int pos=0;
    pos += element_to_bytes(buf + pos, PID1i);
    pos += element_to_bytes(buf + pos, PID2i);
    pos += element_to_bytes(buf + pos, B);   
    memcpy(buf+pos, data, strlen(data));
    pos += strlen(data);
    memcpy(buf+pos, t, strlen(t));
    pos += strlen(t);
    hash_to_zr(out, buf, pos);
    return 0;
}
int sha1_binary(const char *msg, unsigned char *hash_out) {
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    unsigned int len;
    EVP_DigestInit_ex(ctx, EVP_sha1(), NULL);
    EVP_DigestUpdate(ctx, msg, strlen(msg));
    EVP_DigestFinal_ex(ctx, hash_out, &len);
    EVP_MD_CTX_free(ctx);
    return 0;
}
void Setup(element_t P, element_t Y, element_t Z, element_t y, element_t z) {

   
    element_mul_zn(Y, P, y);
    element_mul_zn(Z, P, z);  
}

void Keygeneration(element_t xi, element_t Xi, element_t Vi, element_t P){
    element_random(xi);
    element_mul_zn(Xi, P, xi);
}

void Extraction(element_t ai, element_t PID1i, element_t PID2i, element_t Xi, element_t y, element_t z, element_t P, element_t Vi, pairing_t pairing) {
    element_t xi, h1i, h2i, xiZ;
    element_init_Zr(xi, pairing);   
    element_random(xi);
    element_mul_zn(PID1i, P, xi);
    element_init_G1(xiZ, pairing);
    element_mul_zn(xiZ, PID1i, z);
    element_init_G1(h2i, pairing);
    element_from_hash(h2i, xiZ, 20);
    element_add(PID2i, Vi, h2i);

    element_init_Zr(h1i, pairing);
    int ret=H1(h1i, PID1i, PID2i, Xi);
    element_mul(ai, h1i, y);
    element_add(ai, ai, xi);
    element_clear(xi);
    element_clear(xiZ);
    element_clear(h2i);
    element_clear(h1i);

}/*Partial Private Key Extraction*/

void Forge(pairing_t pairing, Vehicle vehicles[40], element_t S, const char **m, const char *t, element_t P, element_t Y){
    element_t h1i, h3i, temp_Zr;
    element_t  P1_agg, P2_agg, P3_agg, P4_agg, temp_G1, temp_G2, e_right;
    element_init_Zr(h1i, pairing);
    element_init_Zr(h3i, pairing);
    element_init_Zr(temp_Zr, pairing);
    element_init_G1(P1_agg, pairing);
    element_init_G1(P2_agg, pairing);
    element_init_G1(P3_agg, pairing);
    element_init_G1(P4_agg, pairing);   
    element_init_G1(temp_G1, pairing);
    element_init_G1(temp_G2, pairing);
    element_init_G1(e_right, pairing);
    element_set0(P1_agg);
    element_set0(P2_agg);
    element_set0(P3_agg);
    element_set0(P4_agg);
    
    for(int i=1; i<40; i++){


       const char *mi = m[i]; 
       element_random(vehicles[i].PID1i);// 🔥 vehicle V_i's identity/pseudonym is randomly generated by the adversary.
       element_random(vehicles[i].PID2i);
       element_random(vehicles[i].Xi);// 🔥 vehicle V_i's public key is randomly generated by the adversary.
       element_random(vehicles[i].U);       
        H1(h1i, vehicles[i].PID1i, vehicles[i].PID2i, vehicles[i].Xi);        // h_1i = H1(PID_i)
        H3(h3i, vehicles[i].PID1i, vehicles[i].PID2i, vehicles[i].U, mi, t); // h_3i= H3(PID_i, m[i], t)
        element_mul_zn(temp_G1, vehicles[i].Xi, h3i);//h_3i·X_i

        element_add(temp_Zr, temp_Zr, h1i);
        element_add(P1_agg, P1_agg, vehicles[i].U);//Σ B_i
        element_add(P2_agg, P2_agg, vehicles[i]. PID1i);//Σ A_i
        element_add(P3_agg, P3_agg, temp_G1); // Σ h_3i·X_i
        
    }     
        
        
        element_mul_zn(P4_agg, Y, temp_Zr);
        element_printf("The P4 is %B\n", P4_agg);
        element_add(e_right, P1_agg, P2_agg);
        element_add(e_right, P3_agg, e_right);
        element_add(e_right, P4_agg, e_right);
        
        element_neg(vehicles[0].U, e_right);
       const char *mi = m[0];         
        H3(h3i, vehicles[0].PID1i, vehicles[0].PID2i, vehicles[0].U, mi, t); 
        element_mul(S, h3i, vehicles[0].xi);
        element_add(S, vehicles[0].ai, S);
        
        element_clear(h1i);
        element_clear(h3i);
        element_clear(temp_Zr);
        element_clear(P1_agg);
        element_clear(P2_agg);
        element_clear(P3_agg);
        element_clear(P4_agg);   
        element_clear(temp_G1);
        element_clear(temp_G2);
        element_clear(e_right);

        
    
    
}/*the adversary only has vehicle[0].ai and vehicle[0].xi*/


/*The aggregate-verification algorithm is identical to the LPCIA scheme*/
int aggregate_verify(pairing_t pairing, Vehicle vehicles[40],      element_t S,     const char **m,        const char *t,            element_t P,    element_t Y) {
    
    int result = 0;


    element_t  P1_agg, P2_agg, P3_agg, P4_agg, Ti, Xi, temp_G1, temp_G2;
    element_t  h1i, h3i;
    element_t e_left, e_right, PID1i, PID2i;

 

    element_init_G1(P1_agg, pairing);
    element_init_G1(P2_agg, pairing);
    element_init_G1(P3_agg, pairing);
    element_init_G1(P4_agg, pairing);
    element_init_G1(temp_G1, pairing);
    element_init_G1(temp_G2, pairing);
    element_init_G1(PID1i, pairing);
    element_init_G1(PID2i, pairing);
    element_init_G1(Ti, pairing);
    element_init_G1(Xi, pairing);

    element_init_Zr(h1i, pairing);
    element_init_Zr(h3i, pairing);



    element_init_G1(e_left, pairing);
    element_init_G1(e_right, pairing);

   

    element_set0(P1_agg);
    element_set0(P2_agg);
    element_set0(P3_agg);
    element_set0(P4_agg);

    // ===================== =====================
    for (int i = 0; i < 40; i++) {
        element_set(PID1i, vehicles[i].PID1i);
        element_set(PID2i, vehicles[i].PID2i);
        element_set(Ti, vehicles[i].U);
        element_set(Xi, vehicles[i].Xi);
        const char *mi = m[i]; // 

        H1(h1i, PID1i, PID2i, Xi);        
        H3(h3i, PID1i, PID2i, vehicles[i].U, mi, t); 
        element_mul_zn(temp_G1, Xi, h3i);
        element_mul_zn(temp_G2, Y, h1i);
        element_add(P1_agg, P1_agg, Ti);
        element_add(P2_agg, P2_agg, PID1i);
        element_add(P3_agg, P3_agg, temp_G1); 
        element_add(P4_agg, P4_agg, temp_G2);
        
    }     
        
        element_mul_zn(e_left, P, S);   
        
        element_add(e_right, P1_agg, P2_agg);
        element_add(e_right, P3_agg, e_right);
        element_add(e_right, P4_agg, e_right);
      
  
 
    result = (element_cmp(e_left, e_right) == 0) ? 1 : 0;

    
    element_clear(P1_agg);
    element_clear(P2_agg);
    element_clear(P3_agg);
    element_clear(P4_agg);
    element_clear(temp_G1);
    element_clear(temp_G2);
    element_clear(h1i);
    element_clear(h3i);
    element_clear(Ti);
    element_clear(Xi);
    element_clear(e_left);
    element_clear(e_right);
    element_clear(PID1i);
    element_clear(PID2i);
    return result;
  
}/*The aggregate-verification algorithm is identical to the LPCIA scheme*/


int main()
{   Vehicle V[40];
    pairing_t pairing;
     pbc_param_t param;
     struct timespec start, end, start1, end1, start2, end2, start3, end3, start4, end4, start5, end5, start6, end6, start7, end7, start8, end8, start12, end12, start_12, end_12;
     double elapsed, elapsed1, elapsed2, elapsed3, elapsed4, elapsed5, elapsed6, elapsed7, elapsed8, elapsed12, elapsed_12;
    pbc_param_init_a_gen(param, 160, 512);
     pairing_init_pbc_param(pairing, param);
    const char *msgs[40] = {
    "model 1", "model 2", "model 3", "model 4", "model 5",
    "model 6", "model 7", "model 8", "model 9", "model 10",
    "model 11","model 12","model 13","model 14","model 15",
    "model 16","model 17","model 18","model 19","model 20",
    "model 21", "model 22", "model 23", "model 24", "model 25",
    "model 26", "model 27", "model 28", "model 29", "model 30",
    "model 31","model 32","model 33","model 34","model 35",
    "model 36","model 37","model 38","model 39","model 40"
     };
    const char *t="5th iteration";
    unsigned char hash_bin[20];
    sha1_binary(t, hash_bin);
    char hex_hash[41];  
    element_t P, Q, B, Y, Z, y, z, h1i, h2i, h3i,  Vi[40], S, left, right;
    element_init_Zr(h1i, pairing);
    element_init_G1(h2i, pairing);
    element_init_Zr(h3i, pairing);
    element_init_G1(left, pairing);
    element_init_G1(right, pairing);
    element_init_Zr(S, pairing);
    
     for(int i=0; i<40; i++){
         element_init_G1(Vi[i], pairing);
         element_random(Vi[i]);
         element_init_G1(V[i].PID1i, pairing);
         element_init_G1(V[i].PID2i, pairing);
         element_init_Zr(V[i].ai, pairing); 
         element_init_G1(V[i].U, pairing);
         element_init_G1(V[i].Xi, pairing);
         element_init_Zr(V[i].xi, pairing);
    }

         

    
    element_init_Zr(z, pairing);
    element_init_Zr(y, pairing);
    element_init_G1(P, pairing);
    element_init_G1(Y, pairing);
    element_init_G1(Z, pairing);
    element_init_G1(Q, pairing);
    element_random(z);
    element_random(y);
    element_random(P);
    element_random(Q);
    
    clock_gettime(CLOCK_MONOTONIC, &start);

    Setup(P, Y, Z, y, z);
    
    clock_gettime(CLOCK_MONOTONIC, &end); 
    
    
    elapsed = ((end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1e9)/20;   
   
    Keygeneration(V[0].xi, V[0].Xi, Vi[0], P);// 🔥 Only V_0's public key is legal.
  
    
    clock_gettime(CLOCK_MONOTONIC, &start1);
   
    Extraction(V[0].ai, V[0].PID1i, V[0].PID2i, V[0].Xi, y, z, P, Vi[0], pairing); // 🔥 The TA only generate V_0's partial private key c_0.
    
     clock_gettime(CLOCK_MONOTONIC, &end1); 
     elapsed1 = ((end1.tv_sec - start1.tv_sec) + (end1.tv_nsec - start1.tv_nsec) / 1e9)/40;   
       
    
    clock_gettime(CLOCK_MONOTONIC, &start12);

      element_mul_zn(left, P, V[0].ai);
      H1(h1i, V[0].PID1i, V[0].PID2i, V[0].Xi);
      element_mul_zn(right, Y, h1i);
      element_add(right, right, V[0].PID1i);
      if (element_cmp(left, right) == 0) {
          printf("0th Key is generated!\n"); 
    
          } else {
          printf("0th Key is not generated!\n"); 
          }//verify the partial private key
    
    clock_gettime(CLOCK_MONOTONIC, &end12); 
  elapsed12 = ((end12.tv_sec - start12.tv_sec) + (end12.tv_nsec - start12.tv_nsec) / 1e9)/40;   
     
     
   
 
    Forge(pairing, V, S, msgs, t, P, Y);// 🔥 Other 39 private keys are generated by the forgery algorithm. S is the aggregate signature.
      
   
    int result=aggregate_verify(pairing, V, S, msgs,   t, P, Y);// 🔥 It it identical to the LPCIA scheme.
    if(result)
       printf("The aggregate signature is valid!\n");
    else
       printf("The aggregate signature is not valid");
    
   
    element_clear(h1i);
    element_clear(h2i);
    element_clear(h3i);
    //element_clear(B);
   

    for(int i=0; i<20; i++){
       element_clear(V[i].PID1i);
       element_clear(V[i].PID2i);
       element_clear(V[i].ai); 
       element_clear(Vi[i]);
       element_clear(V[i].Xi);
       element_clear(V[i].xi);
}

   
   element_clear(S);
    element_clear(z);
    element_clear(y);
    pairing_clear(pairing);
     pbc_param_clear(param);
    return 0;
}


